services:
  postgres:
    image: postgres:16.4
    container_name: hotel-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hotel
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  auth-service:
    build:
      context: C:\Users\TinqinGuest\Documents\GitHub\authentication
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hotel-db:5432/auth
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  comments-service:
    build:
      context: C:\Users\TinqinGuest\Documents\GitHub\comments
      dockerfile: Dockerfile
    container_name: comments-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hotel-db:5432/comments
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  hotel-service:
    build:
      context: C:\Users\TinqinGuest\Documents\GitHub\Hotel
      dockerfile: Dockerfile
    container_name: hotel-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hotel-db:5432/hotel
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  bff-service:
    build:
      context: C:\Users\TinqinGuest\Documents\GitHub\HotelBff
      dockerfile: Dockerfile
    container_name: bff-service
    environment:
      - HOTEL_SERVICE_URL=http://hotel-service:8080
      - AUTH_SERVICE_URL=http://auth-service:8083
      - COMMENTS_SERVICE_URL=http://comments-service:8082
    ports:
      - "8081:8081"
    depends_on:
      - hotel-service
      - auth-service
      - comments-service

volumes:
  db-volume:
